<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Facility Name_facName</name>
   <tag></tag>
   <elementGuidId>e5c38b52-380a-40e4-bb94-4d5a35036f31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;facName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='facName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd6d3d69-43d1-4e98-8542-ea3800f96338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2dab6dbd-4640-4650-8af0-ebcaf6d8b12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>facName</value>
      <webElementGuid>d0542b20-1aa0-4568-9b98-f824e1970685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formfieldXL</value>
      <webElementGuid>f8a51169-50c2-4c6b-a3dc-3ed0e832971e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectiond&quot;)/div[1]/div[@class=&quot;box_T&quot;]/div[@class=&quot;box_L&quot;]/div[@class=&quot;box_R&quot;]/div[@class=&quot;box_B&quot;]/div[@class=&quot;box_TL&quot;]/div[@class=&quot;box_TR&quot;]/div[@class=&quot;box_BL&quot;]/div[@class=&quot;box_BR&quot;]/div[@class=&quot;textbox_center&quot;]/table[1]/tbody[1]/tr[1]/td[2]/div[@class=&quot;formfieldXL_BG&quot;]/input[@class=&quot;formfieldXL&quot;]</value>
      <webElementGuid>ad20c84b-2340-4536-9e4e-6f52f97f65c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='facName']</value>
      <webElementGuid>7631b9d4-7048-4868-9013-287c198f4492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectiond']/div/div/div/div/div/div/div/div/div/div/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>4d0cc08f-271b-4ac8-be15-4b6e1a7f698d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/div/div/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>9143d5ff-b632-4413-ad31-02894384e0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'facName']</value>
      <webElementGuid>c0aedecf-2951-4cb8-a3f7-cf2c73dbe732</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
