<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CRFs</name>
   <tag></tag>
   <elementGuidId>1ce64ba4-868d-4a05-b4f7-eac3c0c14a2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subnav_Tasks']/div/div[6]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c80eb225-0d65-4ccc-96eb-ed16b9318c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lc120/ListCRF?module=manage</value>
      <webElementGuid>f45f5a6e-6e20-4139-b62d-00263f82b91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CRFs</value>
      <webElementGuid>c2890011-4a0a-45db-a0bd-d8effd7eee2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subnav_Tasks&quot;)/div[@class=&quot;dropdown_BG&quot;]/div[@class=&quot;taskRightColumn&quot;]/div[@class=&quot;taskLink&quot;]/a[1]</value>
      <webElementGuid>5b0f1410-1eee-453a-85f0-f5f2695bb99f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subnav_Tasks']/div/div[6]/div[2]/a</value>
      <webElementGuid>94b26dfa-26dc-4001-9f72-3b955f7196d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CRFs')]</value>
      <webElementGuid>7bb6dcf5-b53b-45b6-b9c3-99dffcbe634e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Groups'])[1]/following::a[1]</value>
      <webElementGuid>91407246-3583-44a3-af82-7d8adef0152b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rules'])[1]/following::a[2]</value>
      <webElementGuid>47d5e574-2000-43ea-80fe-a13c2a3c77cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extract Data'])[1]/preceding::a[1]</value>
      <webElementGuid>69306830-3680-477f-851f-4a8e85bc12a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Datasets'])[1]/preceding::a[1]</value>
      <webElementGuid>63670dbe-9343-46f9-a54a-8998a43450a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CRFs']/parent::*</value>
      <webElementGuid>ba8f133c-5802-4e66-8225-a82f7d6c6c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lc120/ListCRF?module=manage')]</value>
      <webElementGuid>cfe1dd74-9149-40d3-baec-5307c8577660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/a</value>
      <webElementGuid>5c8e8cdb-ebdd-493b-96a0-bde85c4cb99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/lc120/ListCRF?module=manage' and (text() = 'CRFs' or . = 'CRFs')]</value>
      <webElementGuid>70de6f83-551c-46cf-87c6-7c915b8f00a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
