<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tasks</name>
   <tag></tag>
   <elementGuidId>546e7107-ef3e-45fb-b4f0-e38944166dc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav_Tasks_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav_Tasks_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49c1414b-42f3-4c0c-950c-c2967ca121a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5d11877e-819f-46e6-9dcd-1ace96e450e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>setNav('nav_Tasks');</value>
      <webElementGuid>e59c5223-015e-481e-8943-2c24a3c0fad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav_Tasks_link</value>
      <webElementGuid>daabbdfa-184c-473f-9310-be64fdaeb3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tasks
                                                </value>
      <webElementGuid>83c64ce0-e8ee-426a-8f89-fa92360c5523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_Tasks_link&quot;)</value>
      <webElementGuid>1adbfcf4-1c2f-467e-934d-4475669db2af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav_Tasks_link']</value>
      <webElementGuid>7cce1321-a56e-49eb-8a86-b0f9f8c37eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav_Tasks']/a</value>
      <webElementGuid>f33b572c-4a60-41a3-8b3d-0ccdb2b91cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tasks')]</value>
      <webElementGuid>4dd40ea8-87de-47e9-ad2e-5176a7c460af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Study Audit Log'])[1]/following::a[1]</value>
      <webElementGuid>28c8c03d-ed37-48db-852e-282bd66d89f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Data'])[1]/preceding::a[2]</value>
      <webElementGuid>6444e369-9f42-49f1-98fa-f0029c69cde6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject Matrix'])[2]/preceding::a[2]</value>
      <webElementGuid>19f2bb88-44b6-4e15-8dbd-1cbc4cb6e3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tasks']/parent::*</value>
      <webElementGuid>74d956d1-7f39-44c3-a2c2-6ad365cabdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>0aeed0c4-df40-41bc-9991-2a4bf23e0680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>1023a2e7-0ca6-4d10-85a0-401893fbd461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'nav_Tasks_link' and (text() = 'Tasks
                                                ' or . = 'Tasks
                                                ')]</value>
      <webElementGuid>e4161dae-b67d-4278-ba4f-404203aee7f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
