<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Send User Password via EmailShow User_7f317d</name>
   <tag></tag>
   <elementGuidId>979c8045-0780-4d50-9578-e79d5b7ca459</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#displayPwd1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='displayPwd1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ab6dd02-59db-4edd-9740-3162f33d3e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e8c73d7f-9c39-4a65-b5f9-6ab5e6b65397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>displayPwd1</value>
      <webElementGuid>1a006bcb-0ea6-4e5e-b9a9-bd1b49ced9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>displayPwd</value>
      <webElementGuid>6c643370-3f4a-4f9f-8201-4d091e28b133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>1f08eb86-4601-4c32-9748-554849303ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayPwd1&quot;)</value>
      <webElementGuid>332f5529-fc8a-4cf2-8560-6c163219d111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='displayPwd1']</value>
      <webElementGuid>2efca32a-b4d7-45df-bd9d-25082960ca22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>973afaf0-7441-4f78-bcc9-ccd06675019f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'displayPwd1' and @name = 'displayPwd']</value>
      <webElementGuid>7b090ab6-d7d5-4385-8acb-107c530cf997</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
