<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Institutional Affiliation_institution_116f0c</name>
   <tag></tag>
   <elementGuidId>666eeb3c-5541-4fb7-b26e-722fa49cb39d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#institutionalAffiliation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='institutionalAffiliation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47e56e08-f49b-40bb-8b02-a115d0cb6cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ad2907a-7b4a-44c9-a79d-b404d2f75f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>institutionalAffiliation</value>
      <webElementGuid>8d6da6af-0fb6-479e-930d-81f395adb92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>institutionalAffiliation</value>
      <webElementGuid>9a970891-f1b0-4ae7-948f-ca7570371fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>eda12df6-37b0-41c8-b142-f9d27b2ec79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formfieldM</value>
      <webElementGuid>6a4f8123-7a13-4a4c-9ee9-9391ea8164b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;institutionalAffiliation&quot;)</value>
      <webElementGuid>b1c06e33-2a36-4014-abcc-9c43e9306d10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='institutionalAffiliation']</value>
      <webElementGuid>5edb3709-fa05-4363-8ea6-651f38228a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/table/tbody/tr/td/div/input</value>
      <webElementGuid>ea9b457f-073b-488a-aa0d-a732977cfec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'institutionalAffiliation' and @name = 'institutionalAffiliation']</value>
      <webElementGuid>b30fa0a9-8c95-4b21-984c-c06b6051b8d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
