<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Clear Search Keywords</name>
   <tag></tag>
   <elementGuidId>419f0489-5360-4658-96fa-6c472de16a0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Clear Search Keywords')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.table_tools > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>08e14963-1e7a-4df7-bf77-dacfb761ccf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>ListCRF?submitted=1&amp;module=manage&amp;ebl_page=1&amp;ebl_sortColumnInd=0&amp;ebl_sortAscending=1&amp;ebl_filtered=0&amp;ebl_filterKeyword=&amp;ebl_paginated=1</value>
      <webElementGuid>5d69b558-d56b-4cf0-bf1d-b05f308f4867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clear Search Keywords</value>
      <webElementGuid>0f53be36-65ae-4763-a0cb-3111a2054b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main_BG&quot;]/table[@class=&quot;background&quot;]/tbody[1]/tr[1]/td[1]/table[2]/tbody[1]/tr[1]/td[@class=&quot;aka_revised_content&quot;]/table[1]/tbody[1]/tr[1]/td[1]/div[@class=&quot;box_T&quot;]/div[@class=&quot;box_L&quot;]/div[@class=&quot;box_R&quot;]/div[@class=&quot;box_B&quot;]/div[@class=&quot;box_TL&quot;]/div[@class=&quot;box_TR&quot;]/div[@class=&quot;box_BL&quot;]/div[@class=&quot;box_BR&quot;]/div[@class=&quot;tablebox_center&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;table_actions&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;table_tools&quot;]/a[1]</value>
      <webElementGuid>038f1d5b-e1e5-4ed3-950b-fa9530c7ec28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>048b4a31-68a9-4bf0-9108-4fcef6dfb9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>ListCRF?submitted=1&amp;module=manage&amp;ebl_page=1&amp;ebl_sortColumnInd=0&amp;ebl_sortAscending=1&amp;ebl_filtered=0&amp;ebl_filterKeyword=&amp;ebl_paginated=1</value>
      <webElementGuid>f8b84a08-ddcf-4be0-b282-9914502485c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clear Search Keywords</value>
      <webElementGuid>7031bc42-4852-4a83-a3cc-5c353f9b72cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main_BG&quot;]/table[@class=&quot;background&quot;]/tbody[1]/tr[1]/td[1]/table[2]/tbody[1]/tr[1]/td[@class=&quot;aka_revised_content&quot;]/table[1]/tbody[1]/tr[1]/td[1]/div[@class=&quot;box_T&quot;]/div[@class=&quot;box_L&quot;]/div[@class=&quot;box_R&quot;]/div[@class=&quot;box_B&quot;]/div[@class=&quot;box_TL&quot;]/div[@class=&quot;box_TR&quot;]/div[@class=&quot;box_BL&quot;]/div[@class=&quot;box_BR&quot;]/div[@class=&quot;tablebox_center&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;table_actions&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;table_tools&quot;]/a[1]</value>
      <webElementGuid>beeea942-5e71-40b5-a3d8-b5c91d6a02ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Clear Search Keywords')]</value>
      <webElementGuid>7a3f09dc-0425-423d-9b33-34c8650edf61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1 of 1'])[1]/following::a[1]</value>
      <webElementGuid>3ee1242b-88e8-48f5-ab95-3414dd9d89c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Case Report Forms (CRFs)'])[1]/following::a[1]</value>
      <webElementGuid>4ea92d92-18e4-410e-bec2-8ef8ac5374d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blank CRF Template'])[1]/preceding::a[1]</value>
      <webElementGuid>8c7355dc-c837-43e7-ad49-4dbdc8f0391f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clear Search Keywords']/parent::*</value>
      <webElementGuid>8abe8007-b4d0-48ab-bd75-6f633d493671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'ListCRF?submitted=1&amp;module=manage&amp;ebl_page=1&amp;ebl_sortColumnInd=0&amp;ebl_sortAscending=1&amp;ebl_filtered=0&amp;ebl_filterKeyword=&amp;ebl_paginated=1')]</value>
      <webElementGuid>dd704bd1-a787-463c-8035-f7adc5c1bf87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr/td/a</value>
      <webElementGuid>88bc87fc-f16d-4793-847d-a6ebd891de62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'ListCRF?submitted=1&amp;module=manage&amp;ebl_page=1&amp;ebl_sortColumnInd=0&amp;ebl_sortAscending=1&amp;ebl_filtered=0&amp;ebl_filterKeyword=&amp;ebl_paginated=1' and (text() = 'Clear Search Keywords' or . = 'Clear Search Keywords')]</value>
      <webElementGuid>03543be9-a0cb-4807-bcd7-108167767993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
