<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CRFs</name>
   <tag></tag>
   <elementGuidId>15a6ef70-f027-401a-80a1-f5ce05435121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subnav_Tasks']/div/div[6]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>467927b9-ee98-44f9-8425-2942a73250cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lc120/ListCRF?module=manage</value>
      <webElementGuid>f7ddf5bf-dc73-43c7-a5ae-a8d59f3ab595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CRFs</value>
      <webElementGuid>7e03355f-dca0-48b0-af41-4898f90f9bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subnav_Tasks&quot;)/div[@class=&quot;dropdown_BG&quot;]/div[@class=&quot;taskRightColumn&quot;]/div[@class=&quot;taskLink&quot;]/a[1]</value>
      <webElementGuid>1b6c2aba-9734-4166-b2fc-701016997f96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subnav_Tasks']/div/div[6]/div[2]/a</value>
      <webElementGuid>01508133-1d1b-4345-b365-530055b1e003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CRFs')]</value>
      <webElementGuid>2605660a-7982-48d4-8d40-56bd67199b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Groups'])[1]/following::a[1]</value>
      <webElementGuid>b36e67fc-0d7e-4195-ba43-3b990020c4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rules'])[1]/following::a[2]</value>
      <webElementGuid>13bf8bca-03b8-4af9-8d22-babd2db35fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extract Data'])[1]/preceding::a[1]</value>
      <webElementGuid>d7dd2a7b-c2b3-4462-af95-a86bdd367085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Datasets'])[1]/preceding::a[1]</value>
      <webElementGuid>6bd4eaf8-7e40-465c-afc8-d419004b7a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CRFs']/parent::*</value>
      <webElementGuid>bc727e00-0fc9-4f4b-bd9f-c644612d4d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lc120/ListCRF?module=manage')]</value>
      <webElementGuid>ff3554d2-e0af-4921-b08e-3ca3d1ae85d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/a</value>
      <webElementGuid>91130815-5dbd-4b98-a998-b48b4f718672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/lc120/ListCRF?module=manage' and (text() = 'CRFs' or . = 'CRFs')]</value>
      <webElementGuid>48e91287-d1df-47aa-ba17-fe5a45e75fe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
